version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_HOST: host.docker.internal
      MYSQL_ROOT_PASSWORD: Abc@123456789
      MYSQL_DATABASE: makemytripfinal
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - makemytrip_network
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Abc@123456789
      - MYSQL_DB=makemytripfinal
      - FLASK_ENV=development
    depends_on:
      db:
        condition: service_healthy
    networks:
      - makemytrip_network


volumes:
  mysql_data:

networks:
  makemytrip_network:
    driver: bridge